# Generated by Django 4.1.1 on 2022-10-03 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_question_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='tags_string',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(blank=True, to='main.tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
