# Generated by Django 3.2.13 on 2022-10-04 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_question_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(to='main.Tag'),
        ),
        migrations.AlterField(
            model_name='question',
            name='tags_string',
            field=models.CharField(max_length=128),
        ),
    ]
