# Generated by Django 4.1.1 on 2022-10-07 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_rename_add_dislike_answervote_event_dislike_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answervote',
            name='add_dislike',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='answervote',
            name='add_like',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questionvote',
            name='add_dislike',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questionvote',
            name='add_like',
            field=models.BooleanField(default=False),
        ),
    ]
