# Generated by Django 4.1.1 on 2022-09-30 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='avatar',
            field=models.ImageField(null=True, upload_to='siteauth/'),
        ),
    ]
