# Generated by Django 3.2.13 on 2022-09-26 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_answervote_value_remove_questionvote_value_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='content',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='content',
            new_name='body',
        ),
        migrations.AddField(
            model_name='question',
            name='slug',
            field=models.SlugField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
