# Generated by Django 3.2.13 on 2022-10-05 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_tag_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='is_correct',
            new_name='is_favorite',
        ),
    ]
