name: Pylint

on: [push]
env:
  #Set environment variables
  REDIS_HOST: localhost
  REDIS_PORT:  6379
  REDIS_TIMEOUT: 3

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install redis
        pip install fakeredis
        pip install fakeredis python-dotenv
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
    - name: Install redis
      run: |
        sudo apt-get install -y redis-server
    - name: Run python tests
      run: |
        cd homework4
        python -m unittest
